# Form implementation generated from reading ui file '.\Contabilidad.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Contabilidad(object):
    def setupUi(self, Contabilidad):
        Contabilidad.setObjectName("Contabilidad")
        Contabilidad.resize(685, 559)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Contabilidad.sizePolicy().hasHeightForWidth())
        Contabilidad.setSizePolicy(sizePolicy)
        Contabilidad.setMinimumSize(QtCore.QSize(685, 559))
        Contabilidad.setMaximumSize(QtCore.QSize(685, 559))
        self.centralwidget = QtWidgets.QWidget(parent=Contabilidad)
        self.centralwidget.setObjectName("centralwidget")
        self.tableContabilidad = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableContabilidad.setGeometry(QtCore.QRect(30, 160, 451, 341))
        self.tableContabilidad.setObjectName("tableContabilidad")
        self.tableContabilidad.setColumnCount(4)
        self.tableContabilidad.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableContabilidad.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableContabilidad.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableContabilidad.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableContabilidad.setHorizontalHeaderItem(3, item)
        self.btnVolver = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnVolver.setGeometry(QtCore.QRect(530, 450, 111, 51))
        self.btnVolver.setObjectName("btnVolver")
        self.lcdTotal = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.lcdTotal.setGeometry(QtCore.QRect(300, 20, 351, 81))
        self.lcdTotal.setObjectName("lcdTotal")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Contabilidad.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Contabilidad)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 21))
        self.menubar.setObjectName("menubar")
        Contabilidad.setMenuBar(self.menubar)

        self.retranslateUi(Contabilidad)
        QtCore.QMetaObject.connectSlotsByName(Contabilidad)

    def retranslateUi(self, Contabilidad):
        _translate = QtCore.QCoreApplication.translate
        Contabilidad.setWindowTitle(_translate("Contabilidad", "MainWindow"))
        item = self.tableContabilidad.horizontalHeaderItem(0)
        item.setText(_translate("Contabilidad", "ID"))
        item = self.tableContabilidad.horizontalHeaderItem(1)
        item.setText(_translate("Contabilidad", "Nombre"))
        item = self.tableContabilidad.horizontalHeaderItem(2)
        item.setText(_translate("Contabilidad", "Fecha"))
        item = self.tableContabilidad.horizontalHeaderItem(3)
        item.setText(_translate("Contabilidad", "Total"))
        self.btnVolver.setText(_translate("Contabilidad", "Volver"))
        self.label.setText(_translate("Contabilidad", "Total de ingresos"))
