# Form implementation generated from reading ui file '.\Inventario.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_inventario(object):
    def setupUi(self, inventario):
        inventario.setObjectName("inventario")
        inventario.resize(800, 600)
        inventario.setMinimumSize(QtCore.QSize(800, 600))
        inventario.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=inventario)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 120, 571, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.btnAgregar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(520, 60, 101, 41))
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnEliminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(630, 60, 101, 41))
        self.btnEliminar.setObjectName("btnEliminar")
        self.btnVolver = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnVolver.setGeometry(QtCore.QRect(670, 480, 101, 51))
        self.btnVolver.setObjectName("btnVolver")
        self.lineProducto = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineProducto.setGeometry(QtCore.QRect(60, 60, 113, 20))
        self.lineProducto.setObjectName("lineProducto")
        self.linePrecio = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.linePrecio.setGeometry(QtCore.QRect(200, 60, 113, 20))
        self.linePrecio.setObjectName("linePrecio")
        self.lineStock = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineStock.setGeometry(QtCore.QRect(340, 60, 113, 20))
        self.lineStock.setObjectName("lineStock")
        inventario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=inventario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        inventario.setMenuBar(self.menubar)

        self.retranslateUi(inventario)
        QtCore.QMetaObject.connectSlotsByName(inventario)

    def retranslateUi(self, inventario):
        _translate = QtCore.QCoreApplication.translate
        inventario.setWindowTitle(_translate("inventario", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("inventario", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("inventario", "Producto"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("inventario", "Precio"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("inventario", "Stock"))
        self.btnAgregar.setText(_translate("inventario", "Agregar"))
        self.btnEliminar.setText(_translate("inventario", "Eliminar"))
        self.btnVolver.setText(_translate("inventario", "Volver"))
        self.lineProducto.setPlaceholderText(_translate("inventario", "Producto"))
        self.linePrecio.setPlaceholderText(_translate("inventario", "Precio"))
        self.lineStock.setPlaceholderText(_translate("inventario", "Stock"))
