# Form implementation generated from reading ui file '.\menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_menuPrincipal(object):
    def setupUi(self, menuPrincipal):
        menuPrincipal.setObjectName("menuPrincipal")
        menuPrincipal.resize(667, 436)
        menuPrincipal.setMinimumSize(QtCore.QSize(667, 436))
        menuPrincipal.setMaximumSize(QtCore.QSize(667, 436))
        self.centralwidget = QtWidgets.QWidget(parent=menuPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnCrm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCrm.setGeometry(QtCore.QRect(140, 180, 111, 51))
        self.btnCrm.setObjectName("btnCrm")
        self.btnInventario = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInventario.setGeometry(QtCore.QRect(420, 180, 111, 51))
        self.btnInventario.setObjectName("btnInventario")
        self.btnEmpleados = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEmpleados.setGeometry(QtCore.QRect(140, 250, 111, 51))
        self.btnEmpleados.setObjectName("btnEmpleados")
        self.btnContabilidad = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnContabilidad.setGeometry(QtCore.QRect(280, 250, 111, 51))
        self.btnContabilidad.setObjectName("btnContabilidad")
        self.btnProyecto = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnProyecto.setGeometry(QtCore.QRect(420, 250, 111, 51))
        self.btnProyecto.setObjectName("btnProyecto")
        self.btnTPV = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTPV.setGeometry(QtCore.QRect(280, 180, 111, 51))
        self.btnTPV.setObjectName("btnTPV")
        menuPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=menuPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 21))
        self.menubar.setObjectName("menubar")
        menuPrincipal.setMenuBar(self.menubar)

        self.retranslateUi(menuPrincipal)
        QtCore.QMetaObject.connectSlotsByName(menuPrincipal)

    def retranslateUi(self, menuPrincipal):
        _translate = QtCore.QCoreApplication.translate
        menuPrincipal.setWindowTitle(_translate("menuPrincipal", "Menú"))
        self.label.setText(_translate("menuPrincipal", "Bienvenido al menú principal"))
        self.btnCrm.setText(_translate("menuPrincipal", "CRM"))
        self.btnInventario.setText(_translate("menuPrincipal", "Inventario"))
        self.btnEmpleados.setText(_translate("menuPrincipal", "Empleados"))
        self.btnContabilidad.setText(_translate("menuPrincipal", "Contabilidad"))
        self.btnProyecto.setText(_translate("menuPrincipal", "Proyectos"))
        self.btnTPV.setText(_translate("menuPrincipal", "TPV"))
